import { describe, it, expect, beforeAll } from 'vitest';
import crypto from 'crypto';
import { deriveOpaquePath, parseOpaquePath } from '@/modules/cctv/opaque-path.helper';

describe('Opaque Path Identity Cryptography', () => {
  beforeAll(() => {
    process.env.CCTV_OPAQUE_PATH_SECRET = 'new-secret-c11';
    process.env.CCTV_STREAM_JWT_SECRET = 'old-jwt-secret-c10';
  });

  it('should derive a valid opaque path using current secret', () => {
    const tenantId = 't1';
    const cameraId = 'c1';
    const streamVersion = 5;

    const path = deriveOpaquePath(tenantId, cameraId, streamVersion);
    expect(path).toMatch(/^c_t1_c1_v5_[a-zA-Z0-9\-_]{32}$/);
  });

  it('should parse and validate a path generated by the current secret', () => {
    const tenantId = 't1';
    const cameraId = 'c1';
    const streamVersion = 5;

    const path = deriveOpaquePath(tenantId, cameraId, streamVersion);
    
    const parsed = parseOpaquePath(path);
    expect(parsed.tenantId).toBe(tenantId);
    expect(parsed.cameraId).toBe(cameraId);
    expect(parsed.streamVersion).toBe(streamVersion);
  });

  it('should parse and validate a legacy C10.5 path', () => {
    const tenantId = 't1';
    const cameraId = 'c1';
    const streamVersion = 5;

    // Simulate C10.5 derivation using JWT secret
    const hmac = crypto.createHmac('sha256', process.env.CCTV_STREAM_JWT_SECRET!);
    hmac.update(`${tenantId}:${cameraId}:${streamVersion}`);
    const hash = hmac.digest('base64url').substring(0, 32);
    const legacyPath = `c_${tenantId}_${cameraId}_v${streamVersion}_${hash}`;

    // Should successfully validate via fallback
    const parsed = parseOpaquePath(legacyPath);
    expect(parsed.tenantId).toBe(tenantId);
    expect(parsed.cameraId).toBe(cameraId);
    expect(parsed.streamVersion).toBe(streamVersion);
  });

  it('should parse and validate using a previous secret (rotation support)', () => {
    const tenantId = 't1';
    const cameraId = 'c1';
    const streamVersion = 5;

    process.env.CCTV_OPAQUE_PATH_SECRET_PREVIOUS = 'rotated-secret';
    // Expiring tomorrow
    process.env.CCTV_OPAQUE_PATH_SECRET_PREVIOUS_VALID_UNTIL = new Date(Date.now() + 86400000).toISOString();

    const hmac = crypto.createHmac('sha256', process.env.CCTV_OPAQUE_PATH_SECRET_PREVIOUS);
    hmac.update(`${tenantId}:${cameraId}:${streamVersion}`);
    const hash = hmac.digest('base64url').substring(0, 32);
    const prevPath = `c_${tenantId}_${cameraId}_v${streamVersion}_${hash}`;

    const parsed = parseOpaquePath(prevPath);
    expect(parsed.tenantId).toBe(tenantId);
    expect(parsed.cameraId).toBe(cameraId);
    expect(parsed.streamVersion).toBe(streamVersion);
  });

  it('should reject a previous secret path if valid-until has expired', () => {
    const tenantId = 't1';
    const cameraId = 'c1';
    const streamVersion = 5;

    process.env.CCTV_OPAQUE_PATH_SECRET_PREVIOUS = 'rotated-secret';
    // Expired yesterday
    process.env.CCTV_OPAQUE_PATH_SECRET_PREVIOUS_VALID_UNTIL = new Date(Date.now() - 86400000).toISOString();

    const hmac = crypto.createHmac('sha256', process.env.CCTV_OPAQUE_PATH_SECRET_PREVIOUS);
    hmac.update(`${tenantId}:${cameraId}:${streamVersion}`);
    const hash = hmac.digest('base64url').substring(0, 32);
    const prevPath = `c_${tenantId}_${cameraId}_v${streamVersion}_${hash}`;

    // Because valid-until expired, it won't check previous secret, 
    // it will fall through to legacy (which fails) and then throw error.
    expect(() => parseOpaquePath(prevPath)).toThrow('Opaque path HMAC validation failed');
  });

  it('should reject forged or tampered paths', () => {
    const path = deriveOpaquePath('t1', 'c1', 5);
    
    // Tamper with tenant
    const forgedPath1 = path.replace('c_t1', 'c_t2');
    expect(() => parseOpaquePath(forgedPath1)).toThrow('HMAC validation failed');

    // Tamper with MAC
    const forgedPath2 = path.slice(0, -1) + (path.endsWith('a') ? 'b' : 'a');
    expect(() => parseOpaquePath(forgedPath2)).toThrow('HMAC validation failed');
  });

  it('should reject paths with invalid format', () => {
    expect(() => parseOpaquePath('c_t1_c1_v5_tooshort')).toThrow('Invalid opaque path format');
    expect(() => parseOpaquePath('invalid_path')).toThrow('Invalid opaque path format');
  });
});
